### ISSUE TITLE
Python 3.10.11 执行结束后一直提示waiting for changes

### ISSUE THREAD

**Issue by landhu** [NaoOtosaka/pytest-choose#1]
结构如下：
![image](https://github.com/NaoOtosaka/pytest-choose/assets/22722402/adfc16d8-a2cb-4662-8447-6130ce3bf7f6)

运行后一直卡在watching:
`D:\PyInvo>pytest select_poc/ --fc="off" --fc-path="./select_poc/choose.json" -fc-coding="utf-8"
============================= test session starts =============================
platform win32 -- Python 3.10.11, pytest-7.1.3, pluggy-1.2.0
rootdir: D:\PyInvo, configfile: -coding=utf-8
plugins: allure-pytest-2.13.2, assume-2.4.3, base-url-2.0.0, choose-0.0.3, html-3.1.1, instafail-0.5.0, metadata-3.0.0, playwright-0.3.3, repeat-0.9.3, xdist-3.3.1
collected 8 items
collected 8 items

select_poc\test_demo.py ........                                         [100%]

============================== 8 passed in 0.03s ==============================
### Watching:   D:\PyInvo
`

把choose卸载后正常

**Comment by NaoOtosaka** [comment]
感谢提出。
我这里复现了，看了一下发现文档里传入fc-coding参数时少了一个“-”，导致参数传入有问题，被xdist捕获到了。
将
`D:\PyInvo>pytest select_poc/ --fc="off" --fc-path="./select_poc/choose.json" -fc-coding="utf-8"`
修正为
`D:\PyInvo>pytest select_poc/ --fc="off" --fc-path="./select_poc/choose.json" --fc-coding="utf-8"`
即可解决。
后面会修正一下文档

**Comment by landhu** [comment]
还有一个问题：
choose.json中只有class，也会报错
`{
  "class": [
    "TestDemo"
  ]
}`

`D:\PyInvo\select_poc>pytest  --fc="on" --fc-path="choose.json" --fc-coding="utf-8"
========================================================================================================== test session starts ===========================================================================================================
platform win32 -- Python 3.10.11, pytest-7.1.3, pluggy-1.2.0
rootdir: D:\PyInvo\select_poc
plugins: allure-pytest-2.13.2, assume-2.4.3, base-url-2.0.0, choose-0.0.3, html-3.1.1, instafail-0.5.0, metadata-3.0.0, playwright-0.3.3, repeat-0.9.3, xdist-3.3.1
collecting ... 

[pytest-choose] Cases list: choose.json
collected 8 items
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\_pytest\main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\_pytest\main.py", line 321, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pluggy\_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pluggy\_callers.py", line 155, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pluggy\_result.py", line 108, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pluggy\_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\_pytest\main.py", line 332, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\_pytest\main.py", line 660, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pluggy\_hooks.py", line 433, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pluggy\_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pluggy\_callers.py", line 155, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pluggy\_result.py", line 108, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pluggy\_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "D:\Program Files\Python310\lib\site-packages\pytest_choose\plugin.py", line 52, in pytest_collection_modifyitems
INTERNALERROR>     if item.name in parse['function']:
INTERNALERROR> KeyError: 'function'
`

**Comment by NaoOtosaka** [comment]
已经调整了过滤的处理逻辑，现在可以只传入class或者function了，当传入空文件时会过滤掉所有用例。
新版本号为0.0.4，已经上传pypi了，镜像源同步可能会比较慢，可以用官方源更新一下
