### ISSUE TITLE
注释或区分文件夹

### ISSUE THREAD

**Issue by landhu** [NaoOtosaka/pytest-choose#2]
在实际应用场景中，用例不一定在一个py文件中，可以分布不同的文件，甚至文件夹
如：
aaa:
   --- test_aaa.py
bbb:
  --- test_bbb.py
这时，如果文件夹多py文件多，在json中，写TestAAA就不知道这个类在哪个文件夹下，json又不能加注释。这种怎么处理。
{
  "class": [
    "TestAAA",
  ]
}

**Comment by NaoOtosaka** [comment]
正常来说当已经知道测试类名或测试方法名时，通过ide的查找功能时可以很快速定位并跳转到对应的文件的。
如果要对json文件中的内容进行注释的话，可能会考虑规定一个规则，比如以@开头的json数组值、以@开头的json对象键不进行解析，作为注释使用，你觉得怎么样

**Comment by landhu** [comment]
Thanks. 现在引入另一个方法，支持json注释的

**Comment by NaoOtosaka** [comment]
如果方便的话可以讲一下使用什么方法吗，后续会结合着优化一下插件XD
