### ISSUE TITLE
json文件多个class未按class顺序执行

### ISSUE THREAD

**Issue by landhu** [NaoOtosaka/pytest-choose#3]
json文件中有多个class
{
  "class": [
    "Testbsd",
    "Testfqa",
    "Testbbc"
  ]
}
执行顺序好像是随机的，并未按class中的顺序来进行

**Comment by NaoOtosaka** [comment]
执行顺序没有做额外处理，这边只做了收集过滤的操作，实际的执行顺序和pytest原生执行顺序是一致的。
pytest一般默认按照字母排序去执行，文件收集排序按照ASCII码进行，上例中实际执行顺序应该是Testbbc->Testbsd->Testfqa， 具体可以去查一下相关文档。
正常来说自动化脚本应该符合顺序无关性，如果的确需要按照指定顺序执行的话可以配合ordering插件使用。
